### ISSUE TITLE
Right click to create class does not appear when VS Code start

### ISSUE THREAD

**Issue by murugappanrm** [jaguadoromero/vscode-php-create-class#20] opened 2023-03-19 03:08 UTC
This extension is wonderful and helps me make my work a lot easier. Now, i am facing this odd problem. When i first start up vs code and after all the extensions have been loaded, i find that when i right click on in the left tree panel, the option to create classes, traits etc do not show. It shows up after I create a php file and use the command palette - Generate Class  Code. 

Anyone facing this problem. My version of the extension is 1.13.1.

**Comment by murugappanrm** [comment] 2023-03-20 21:22
Hi,

Is there are help on the problem that i am facing?

**Comment by jaguadoromero** [comment] 2023-03-21 10:09
@murugappanrm The right click menu is only activated when the extension detects a `composer.json` file in the project, as it is required to detect the namespace. Check if this could be the reason.

**Comment by lexman1958** [comment] 2023-03-21 11:35
@jaguadoromero 

Composer.json file is always there. Its odd, it only happens when i start up vscode. It works fine after i have created a sample class file using command palette. Please refer to my initial post.  

I have attached a zip file containing the source code.

[src.zip](https://github.com/jaguadoromero/vscode-php-create-class/files/11027804/src.zip)

**Comment by jaguadoromero** [comment] 2023-03-21 13:19
I have tried with the code you have provided in the zip, the extension load correctly and the menu appears immediately the workspace is loaded. On what Operating System are you running vscode?

**Comment by murugappanrm** [comment] 2023-03-21 21:29
@jaguadoromero 

I am running on Windows 10.  I have attached the setting.json file as well, just in case you need it.

[settings.zip](https://github.com/jaguadoromero/vscode-php-create-class/files/11033885/settings.zip)

**Comment by jaguadoromero** [comment] 2023-03-22 16:35
@murugappanrm I have tried with a fresh vscode installation in a fresh Windows 10 machine, with only this extension and with your `settings.json` file and the right click menu works well.
Sorry, but I cannot reproduce your problem.

**Comment by lexman1958** [comment] 2023-03-22 22:03
@jaguadoromero 

Ok thank you for all the good effort. From your test, it appears that some other extension may be conflicting. I will try this on a fresh machine and eliminate any extension conflict. 

**Latest Update:**
I found that there was nothing wrong at all. It was all VS code loading lag. After starting up VS Code i waited for about a minute+ then right click worked normally. 


Please close this issue and thank you for all the assistance.

**Closed as completed** 2023-03-23 07:59 UTC
